title: Sam Henkes # your name (or website title) here
logo: "/images/Sam Henkes c257562-web.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Junior in Computer Science at Iowa State University 
  <br><br>
  ISU Game Development Club President 
  <br><br>
  Current Employment:
  <br>
  Thomson Reuters (Software Engineering Intern)
  <br>
  Self-Employed (Software Engineer Contractor)
  <br><br>
  <a href="https://www.linkedin.com/in/sam-henkes-60117816a">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
